#!/usr/bin/env python

import liblo
import sys,time
import serial
import serial.tools.list_ports
from time import sleep

arduino = None
dmxpro = None

def openArduino():
    ports = list(serial.tools.list_ports.comports())
    for p in ports:
        if 'arduino' in p.description.lower():
            print ('ARDUINO detected at ', p.device)
            global arduino
            arduino = serial.Serial(p.device, 9600, timeout=1)

def openDMX():
    ports = list(serial.tools.list_ports.comports())
    for p in ports:
        if 'dmx usb pro' in p.description.lower():
            print ('DMX USB Pro detected at ', p.device)
            global dmxpro
            dmxpro = p.device

while True:

    if not arduino:
        print (arduino)
        openArduino()
    if not dmxpro:
        openDMX()

    if arduino:
        says = arduino.readline()
        if says:
            print(says)

    else:
        sleep(1)
